### ISSUE TITLE
Why mounting /var/lib/docker/containers ?

### ISSUE THREAD

**Issue by rdtr** [ApsOps/filebeat-kubernetes#1]
Hi,

I'm also trying to use filebeat + ELK instead of a default fluentd solution to collect k8s logs, and this repository is really helpful. Thank you!

Could I just ask you why you're mounting the original log stored location /var/lib/docker/containers, not only /var/log/containers with readonly permission? Is it necessary to run this container?

**Comment by shamil** [comment]
log files in `/var/log/containers` are actually symlinks to the `/var/lib/docker/containers`, thus it requires `/var/lib/docker/containers` to be mounted as well

**Comment by rdtr** [comment]
I see, it's just necessary to mount /var/log/containers.
Thank you for the quick reply!😀
