### ISSUE TITLE
variable replacement

### ISSUE THREAD

**Issue by fragtom** [ApsOps/filebeat-kubernetes#2]
In my container, the variables in /etc/filebeat/filebeat.yml wouldn't replaced, how does the process works?

**Comment by ApsOps** [comment]
@fragtom Sorry for the super late reply.

If you look at the daemonset yaml in [README](https://github.com/ApsOps/filebeat-kubernetes/blob/master/README.md#getting-started), you'll see that you need to set environment variables in `env` field - which will be ~replaced~ used in the [config file L10](https://github.com/ApsOps/filebeat-kubernetes/blob/master/filebeat.yml#L10).

The values are not actually changed in config file, but they're reflected when filebeat runs.
