### ISSUE TITLE
Kubernetes system logs

### ISSUE THREAD

**Issue by laszlocph** [ApsOps/filebeat-kubernetes#8]
Seems the Filebeat config only ships the pod logs from /var/log/containers/*.log

I'm running Kubernetes in Rancher where Kubernetes itself is containerized and logs to the standard /var/lib/docker/containers folder. Now these files are not as nicely named as the symlinked ones in /var/log/containers, but they hold very important information, like the kubelet log.

Is this shipper aiming to solve this problem?

I'm happy to contribute, but don't know what strategy to follow..

**Comment by ApsOps** [comment]
@laszlocph I'm not entirely sure how Rancher runs kubelet as a container. One solution that comes to my mind is - configure Rancher to either add kubelet logs or a symlink in /var/log/containers.

IIRC, /var/lib/docker/containers only has container hashes so a bit complicated to get the kubelet container logs.

What do you suggest?

**Comment by laszlocph** [comment]
The only thing I have in mind is 
- Watch the /var/lib/docker/containers folder for log files too (this requires root though)
- Filter out the files that are symlinked to /var/log/containers, since they are already shipped
- Apply the same naming convention that Kube does, so filebeat can parse it

or alternatively:
- Have a sidekick that creates symlinks for the files that are not symlinked. (These are the Kube system containers, like the kubelet)
- Apply the same naming convention. Which requires access to the Docker daemon..

But both are hairy...

**Comment by laszlocph** [comment]
I think this issue is more specific to my deployment scenario, than to this project. So I close it.
